/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.taller.mantenimiento.view;

import com.google.common.base.Predicates;
import com.google.common.collect.Iterables;
import com.taller.mantenimiento.business.domain.dto.ClienteDTO;
import com.taller.mantenimiento.business.domain.dto.ProductoDTO;
import com.taller.mantenimiento.persisntence.crud.MantenimientoProductoCrudRepository;
import com.taller.mantenimiento.persisntence.dao.data.base.ClienteRepository;
import com.taller.mantenimiento.persisntence.dao.data.base.MantenimientoDBRepository;
import com.taller.mantenimiento.persisntence.dao.data.base.MantenimientoProductoRepository;
import com.taller.mantenimiento.persisntence.dao.data.base.MantenimientosDBRepository;
import com.taller.mantenimiento.persisntence.dao.data.base.ProductoDBRepository;
import com.taller.mantenimiento.persisntence.entity.Cliente;
import com.taller.mantenimiento.persisntence.entity.Mantenimientos;
import com.taller.mantenimiento.persisntence.entity.Producto;
import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author karen
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clienteId = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        registroNombre = new java.awt.TextField();
        registroApellidos = new java.awt.TextField();
        registroTelefono = new java.awt.TextField();
        registroCorreo = new java.awt.TextField();
        registroClienteBTN = new javax.swing.JButton();
        modificarCleinte = new javax.swing.JButton();
        registroClave = new java.awt.TextField();
        buscarCliente = new javax.swing.JToggleButton();
        borrarCliente = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        tablaProductos = new javax.swing.JButton();
        tablaClientes = new javax.swing.JButton();
        tablaMantenimientos = new javax.swing.JButton();
        registr = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        registroTotal = new java.awt.TextField();
        registroMantenimientoBTN = new javax.swing.JButton();
        modificarMantenimiento = new javax.swing.JButton();
        idClienteRegistroMantenimiento = new javax.swing.JTextField();
        idProductoRegistroMantenimiento = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cambiarEstado = new javax.swing.JButton();
        fechaEntrega = new java.awt.TextField();
        buscarMantenimiento = new javax.swing.JButton();
        mantenimientoId = new java.awt.TextField();
        labelEstado = new javax.swing.JLabel();
        borrarMantenimiento = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        registroProductoMarca = new java.awt.TextField();
        registroProductoModelo = new java.awt.TextField();
        registroProductoDesc = new java.awt.TextField();
        registroProductoBTN = new javax.swing.JButton();
        modificarProducto = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        comboPorductoCategoria = new javax.swing.JComboBox<>();
        buscarProducto = new javax.swing.JButton();
        productoId = new java.awt.TextField();
        borrarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(203, 220, 253));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Registro Cliente");

        jLabel2.setText("Consultar por ID");

        jLabel3.setText("Clave");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellidos");

        jLabel6.setText("Teléfono");

        jLabel7.setText("Correo");

        registroClienteBTN.setText("Registrar");
        registroClienteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroClienteBTNActionPerformed(evt);
            }
        });

        modificarCleinte.setText("Modificar");
        modificarCleinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarCleinteActionPerformed(evt);
            }
        });

        buscarCliente.setText("Buscar");
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });

        borrarCliente.setText("Borrar");
        borrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(registroClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(registroTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                                .addComponent(registroNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel6)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(registroClienteBTN)))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(modificarCleinte)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                        .addComponent(borrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)
                                    .addComponent(registroApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(registroCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(clienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarCliente)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registroClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registroApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(21, 21, 21)
                        .addComponent(registroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(registroCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registroClienteBTN)
                    .addComponent(modificarCleinte)
                    .addComponent(borrarCliente))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jButton1.setText("Registro");

        tablaProductos.setText("Productos");
        tablaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaProductosActionPerformed(evt);
            }
        });

        tablaClientes.setText("Clientes");
        tablaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaClientesActionPerformed(evt);
            }
        });

        tablaMantenimientos.setText("Mantenimientos");
        tablaMantenimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaMantenimientosActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tablaProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tablaClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tablaMantenimientos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablaMantenimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jButton1)
                .addGap(36, 36, 36)
                .addComponent(tablaProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaMantenimientos)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        registr.setBackground(new java.awt.Color(203, 220, 254));
        registr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Registro Mantenimiento");

        jLabel9.setText("Fecha de Entrega");

        jLabel11.setText("Consultar por ID");

        jLabel13.setText("Estado:");

        jLabel10.setText("Total");

        registroMantenimientoBTN.setText("Registrar");
        registroMantenimientoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroMantenimientoBTNActionPerformed(evt);
            }
        });

        modificarMantenimiento.setText("Modificar");
        modificarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMantenimientoActionPerformed(evt);
            }
        });

        jLabel20.setText("ID Cliente");

        jLabel21.setText("ID Producto");

        cambiarEstado.setText("Cambiar Estado");
        cambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarEstadoActionPerformed(evt);
            }
        });

        buscarMantenimiento.setText("Buscar");
        buscarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMantenimientoActionPerformed(evt);
            }
        });

        labelEstado.setText("---");

        borrarMantenimiento.setText("Borrar");
        borrarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarMantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrLayout = new javax.swing.GroupLayout(registr);
        registr.setLayout(registrLayout);
        registrLayout.setHorizontalGroup(
            registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registrLayout.createSequentialGroup()
                        .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registrLayout.createSequentialGroup()
                                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(registroMantenimientoBTN)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(idProductoRegistroMantenimiento, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idClienteRegistroMantenimiento, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                                .addGap(62, 62, 62))
                            .addGroup(registrLayout.createSequentialGroup()
                                .addComponent(registroTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(81, 81, 81)))
                        .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registrLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registrLayout.createSequentialGroup()
                                        .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(buscarMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mantenimientoId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(registrLayout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(labelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(cambiarEstado))))
                            .addGroup(registrLayout.createSequentialGroup()
                                .addComponent(modificarMantenimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(borrarMantenimiento)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registrLayout.setVerticalGroup(
            registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrLayout.createSequentialGroup()
                        .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel20))
                        .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(idClienteRegistroMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registrLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarMantenimiento))))
                    .addComponent(mantenimientoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idProductoRegistroMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrLayout.createSequentialGroup()
                        .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(labelEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cambiarEstado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registroMantenimientoBTN)
                    .addComponent(modificarMantenimiento)
                    .addComponent(borrarMantenimiento))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(195, 214, 251));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setText("Registro Producto");

        jLabel15.setText("Marca");

        jLabel16.setText("Modelo");

        jLabel17.setText("Descripción");

        jLabel18.setText("Consultar por ID");

        registroProductoBTN.setText("Registrar");
        registroProductoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroProductoBTNActionPerformed(evt);
            }
        });

        modificarProducto.setText("Modificar");
        modificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductoActionPerformed(evt);
            }
        });

        jLabel19.setText("Categoría");

        comboPorductoCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Television", "DVD", "Estereo", "Bocinas", "Audífonos", "Amplificadores", "Microondas", "Otro" }));

        buscarProducto.setText("Buscar");
        buscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductoActionPerformed(evt);
            }
        });

        borrarProducto.setText("Borrar");
        borrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registroProductoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registroProductoBTN)
                            .addComponent(jLabel15))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(modificarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(borrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(registroProductoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(106, 106, 106)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(registroProductoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(comboPorductoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel18)
                                .addGap(19, 19, 19)
                                .addComponent(productoId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel19)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(52, 52, 52)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registroProductoDesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registroProductoMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registroProductoModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(productoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarProducto))
                        .addGap(46, 46, 46)
                        .addComponent(comboPorductoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registroProductoBTN)
                    .addComponent(modificarProducto)
                    .addComponent(borrarProducto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(registr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(registr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroClienteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroClienteBTNActionPerformed

        ClienteDTO clienteDTO = new ClienteDTO();

        String clave = registroClave.getText();
        String nombre = registroNombre.getText();
        String apellidos = registroApellidos.getText();
        Long telefono = Long.parseLong(registroTelefono.getText());
        String correo = registroCorreo.getText();
        clienteDTO.getClientData(clave, nombre, apellidos, telefono, correo);
    }//GEN-LAST:event_registroClienteBTNActionPerformed

    private void registroProductoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroProductoBTNActionPerformed

        ProductoDTO productoDTO = new ProductoDTO();
        
        String marca = registroProductoMarca.getText();
        String modelo = registroProductoModelo.getText();
        String descripcion = registroProductoDesc.getText();
        int categoria = comboPorductoCategoria.getSelectedIndex();

        productoDTO.getProductData(marca, modelo, descripcion, categoria);
        
        
    }//GEN-LAST:event_registroProductoBTNActionPerformed

    private void registroMantenimientoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroMantenimientoBTNActionPerformed
        MantenimientosDBRepository mantenimiento = new MantenimientosDBRepository();

        String idCliente = idClienteRegistroMantenimiento.getText();

        int idProducto = Integer.parseInt(idProductoRegistroMantenimiento.getText());

        double total = Double.parseDouble(registroTotal.getText());

        mantenimiento.saveData(idCliente, idProducto, total, fechaEntrega.getText());
    }//GEN-LAST:event_registroMantenimientoBTNActionPerformed

    private void tablaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaProductosActionPerformed
        new TablaProductos().setVisible(true);
    }//GEN-LAST:event_tablaProductosActionPerformed

    private void tablaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaClientesActionPerformed
        new TablaClientes().setVisible(true);
    }//GEN-LAST:event_tablaClientesActionPerformed

    private void tablaMantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaMantenimientosActionPerformed
        new TablaMantenimiento().setVisible(true);
    }//GEN-LAST:event_tablaMantenimientosActionPerformed

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        ClienteRepository clienteRepository = new ClienteRepository();
        Cliente cliente = clienteRepository.getClient(clienteId.getText());
        registroClave.setText(cliente.getClienteId());
        registroNombre.setText(cliente.getNombre());
        registroApellidos.setText(cliente.getApellidos());
        registroTelefono.setText(String.valueOf(cliente.getCelular()));
        registroCorreo.setText(cliente.getCorreoElectronico());
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void buscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoActionPerformed
        ProductoDBRepository pdbr = new ProductoDBRepository();
        Producto producto = pdbr.getProduct(Integer.valueOf(productoId.getText()));
        registroProductoMarca.setText(producto.getMarca());
        registroProductoModelo.setText(producto.getModelo());
        registroProductoDesc.setText(producto.getDescripcion());
        comboPorductoCategoria.setSelectedIndex(producto.getIdCategoria());
    }//GEN-LAST:event_buscarProductoActionPerformed

    private void buscarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMantenimientoActionPerformed
        MantenimientosDBRepository mdbr = new MantenimientosDBRepository();
        Mantenimientos mantenimientos = mdbr.getMantenimiento(Integer.valueOf(mantenimientoId.getText()));
        idClienteRegistroMantenimiento.setText(mantenimientos.getIdCleinte());
        idProductoRegistroMantenimiento.setText(String.valueOf(mantenimientos.getIdProducto()));
        fechaEntrega.setText(String.valueOf(mantenimientos.getFecha()));
        registroTotal.setText(String.valueOf(mantenimientos.getTotal()));
        if(mantenimientos.isEstado()==false){
            labelEstado.setText("Pendiente");
        }else{
            labelEstado.setText("Terminado");
        }
        
        cambiarEstado.addActionListener((e) -> {
            if(mantenimientos.isEstado()==false){
                labelEstado.setText("Terminado"); 
                mantenimientos.setEstado(true);
            }else{
                labelEstado.setText("Pendiente"); 
                mantenimientos.setEstado(false);
            }
        });
    }//GEN-LAST:event_buscarMantenimientoActionPerformed

    private void cambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarEstadoActionPerformed

    private void modificarCleinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarCleinteActionPerformed
        Cliente cliente = new Cliente(registroClave.getText(), registroNombre.getText(), registroApellidos.getText(), Long.valueOf(registroTelefono.getText()), registroCorreo.getText());
        ClienteRepository clienteRepository = new ClienteRepository();
        clienteRepository.update(registroClave.getText(), cliente);
    }//GEN-LAST:event_modificarCleinteActionPerformed

    private void modificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductoActionPerformed
        Producto producto = new Producto(registroProductoMarca.getText(), registroProductoModelo.getText(), registroProductoDesc.getText(), comboPorductoCategoria.getSelectedIndex());
        ProductoDBRepository pdbr = new ProductoDBRepository();
        pdbr.update(Integer.valueOf(productoId.getText()), producto);
    }//GEN-LAST:event_modificarProductoActionPerformed

    private void modificarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMantenimientoActionPerformed
        boolean estado;
        if(labelEstado.getText().equals("Pendiente")){
            estado = false;
        }else{
            estado = true;
        }
        
        Mantenimientos mantenimientos = new Mantenimientos(idClienteRegistroMantenimiento.getText(), Integer.valueOf(idProductoRegistroMantenimiento.getText()), Double.valueOf(registroTotal.getText()), java.sql.Date.valueOf((fechaEntrega.getText())), estado);
        new MantenimientosDBRepository().update(Integer.valueOf(mantenimientoId.getText()), mantenimientos);       
    }//GEN-LAST:event_modificarMantenimientoActionPerformed

    private void borrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarClienteActionPerformed
        new ClienteRepository().delete(clienteId.getText());
    }//GEN-LAST:event_borrarClienteActionPerformed

    private void borrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarProductoActionPerformed
        new ProductoDBRepository().delete(Integer.valueOf(productoId.getText()));
    }//GEN-LAST:event_borrarProductoActionPerformed

    private void borrarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarMantenimientoActionPerformed
        new MantenimientoDBRepository().delete(Integer.valueOf(mantenimientoId.getText()));
    }//GEN-LAST:event_borrarMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarCliente;
    private javax.swing.JButton borrarMantenimiento;
    private javax.swing.JButton borrarProducto;
    private javax.swing.JToggleButton buscarCliente;
    private javax.swing.JButton buscarMantenimiento;
    private javax.swing.JButton buscarProducto;
    private javax.swing.JButton cambiarEstado;
    private java.awt.TextField clienteId;
    private javax.swing.JComboBox<String> comboPorductoCategoria;
    private java.awt.TextField fechaEntrega;
    private javax.swing.JTextField idClienteRegistroMantenimiento;
    private javax.swing.JTextField idProductoRegistroMantenimiento;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelEstado;
    private java.awt.TextField mantenimientoId;
    private javax.swing.JButton modificarCleinte;
    private javax.swing.JButton modificarMantenimiento;
    private javax.swing.JButton modificarProducto;
    private java.awt.TextField productoId;
    private javax.swing.JPanel registr;
    private java.awt.TextField registroApellidos;
    private java.awt.TextField registroClave;
    private javax.swing.JButton registroClienteBTN;
    private java.awt.TextField registroCorreo;
    private javax.swing.JButton registroMantenimientoBTN;
    private java.awt.TextField registroNombre;
    private javax.swing.JButton registroProductoBTN;
    private java.awt.TextField registroProductoDesc;
    private java.awt.TextField registroProductoMarca;
    private java.awt.TextField registroProductoModelo;
    private java.awt.TextField registroTelefono;
    private java.awt.TextField registroTotal;
    private javax.swing.JButton tablaClientes;
    private javax.swing.JButton tablaMantenimientos;
    private javax.swing.JButton tablaProductos;
    // End of variables declaration//GEN-END:variables
}
